package GUI;

import Eventos.Enums.tipoDeporte;
import Eventos.Enums.tipoEvento;
import Eventos.Enums.tipoMusica;
import Eventos.Evento;
import Usuarios.UsuarioDefault;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Josue Gavidia
 */
public class Sistema extends javax.swing.JFrame {

    //fechita improv
    Calendar fechita = Calendar.getInstance();
    UsuarioDefault toolKit;
    public static Calendar FECHA = Calendar.getInstance();
    public static SimpleDateFormat fechaNeitor = new SimpleDateFormat("DD/MM/YYYY");

    //CORE ---> ARREGLOS QUE CONTIENEN EVENTOS Y USUARIOS
    public static UsuarioDefault usuarios[];
    private Evento tk;

    public static String loggeado;
    private tipoEvento event;
    private tipoDeporte sport;
    private tipoMusica music;

    public Sistema() throws NullPointerException {

        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        tk = new Evento(0, 0, "", "", fechita, 0.0);
        toolKit = new UsuarioDefault("Erick Amaya", "admin", "supersecreto", "administrador", 34);
        usuarios = new UsuarioDefault[10];
        usuarios[0] = toolKit;
        initWindows();
        this.AgeSelector.setSelectedItem(null);
        this.autoridad.setSelectedItem(null);
        this.RealTime.setText(fechaNeitor.format(FECHA.getTime()));
        this.usernameField.setText("admin");
        this.passwordField.setText("supersecreto");
    }

    //MISC METHODS
    //Could be implemented with an interface
    public final void initWindows() {
        MainLogin.setVisible(true);
        MainMenu.setVisible(false);
        BACK2MENU.setVisible(false);
        CrearUser.setVisible(false);
        EditarUser.setVisible(false);
        EliminarUser.setVisible(false);
        CreateUserTemp.setVisible(false);
        SPORT.setVisible(false);
        MUSICAL.setVisible(false);
        RELIGIOSO.setVisible(false);
        eventChooser.setVisible(false);
    }

    public void TUNER(JButton crearEv, JButton editEv, JButton elimEv, JButton verEv, JButton crearUs, JButton editUs, JButton elimUs, JButton tune) {
        JButton[] eventos = {crearEv, editEv, elimEv, verEv};
        JButton[] usuario = {crearUs, editUs, elimUs};

        if (tuner.getText().equals("Administracion de Eventos")) {
            for (int i = 0; i < eventos.length; i++) {
                for (int j = 0; j < usuario.length; j++) {
                    eventos[i].setVisible(false);
                    usuario[j].setVisible(true);
                    tune.setText("Administracion de Usuarios");

                }

            }
        } else if (tuner.getText().equals("Administracion de Usuarios")) {
            for (int k = 0; k < eventos.length; k++) {
                for (int l = 0; l < usuario.length; l++) {
                    eventos[k].setVisible(true);
                    usuario[l].setVisible(false);
                    tune.setText("Administracion de Eventos");
                }

            }
        }

    }

    public void LogOut(JPanel login, JPanel mainMenu) {
        login.setVisible(true);
        mainMenu.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eventChooser = new javax.swing.JPanel();
        R = new javax.swing.JButton();
        D = new javax.swing.JButton();
        M = new javax.swing.JButton();
        CreateUserTemp = new javax.swing.JPanel();
        fname = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pw = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        AgeSelector = new javax.swing.JComboBox<>();
        create = new javax.swing.JToggleButton();
        autoridad = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        SPORT = new javax.swing.JPanel();
        crearDeportivo = new javax.swing.JToggleButton();
        jLabel6 = new javax.swing.JLabel();
        evName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        evCode = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        rent = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        T1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        T2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cantPeople = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        desc = new javax.swing.JTextArea();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        MUSICAL = new javax.swing.JPanel();
        crearDeportivo1 = new javax.swing.JToggleButton();
        jLabel27 = new javax.swing.JLabel();
        evName3 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        rent3 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        cantPeople3 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        desc3 = new javax.swing.JTextArea();
        jLabel41 = new javax.swing.JLabel();
        evCode5 = new javax.swing.JTextField();
        dateChooser = new com.toedter.calendar.JDateChooser();
        jComboBox1 = new javax.swing.JComboBox<>();
        RELIGIOSO = new javax.swing.JPanel();
        crearDeportivo2 = new javax.swing.JToggleButton();
        jLabel34 = new javax.swing.JLabel();
        evName4 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        evCode4 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        rent4 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        T9 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        T10 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        cantPeople4 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        desc4 = new javax.swing.JTextArea();
        MainLogin = new javax.swing.JPanel();
        LoginBtn = new javax.swing.JButton();
        passwordField = new javax.swing.JTextField();
        usernameField = new javax.swing.JTextField();
        MainMenu = new javax.swing.JPanel();
        BACK2MENU = new javax.swing.JButton();
        CrearEvento = new javax.swing.JButton();
        EditarEvento = new javax.swing.JButton();
        EliminarEvento = new javax.swing.JButton();
        VerEvento = new javax.swing.JButton();
        RealTime = new javax.swing.JLabel();
        tuner = new javax.swing.JButton();
        CrearUser = new javax.swing.JButton();
        EditarUser = new javax.swing.JButton();
        EliminarUser = new javax.swing.JButton();
        LOGOUT = new javax.swing.JButton();
        verEVENTO = new javax.swing.JPanel();
        TITLE = new javax.swing.JLabel();
        TITLE1 = new javax.swing.JLabel();
        cantidad_personas = new javax.swing.JLabel();
        tipo_evento = new javax.swing.JLabel();
        codigo_evento = new javax.swing.JLabel();
        TITLE5 = new javax.swing.JLabel();
        titulo_evento = new javax.swing.JLabel();
        TITLE7 = new javax.swing.JLabel();
        TITLE8 = new javax.swing.JLabel();
        descripcion_evento = new javax.swing.JLabel();
        TITLE9 = new javax.swing.JLabel();
        fecha_evento = new javax.swing.JLabel();
        TITLE10 = new javax.swing.JLabel();
        equipo1_evento = new javax.swing.JLabel();
        TITLE11 = new javax.swing.JLabel();
        equipo2_evento = new javax.swing.JLabel();
        TITLE12 = new javax.swing.JLabel();
        equipo2_evento1 = new javax.swing.JLabel();
        TITLE13 = new javax.swing.JLabel();
        equipo2_evento2 = new javax.swing.JLabel();
        TITLE14 = new javax.swing.JLabel();
        equipo2_evento3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        teamList2_evento = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        musicosYcargo_evento = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        teamList1_evento2 = new javax.swing.JList<>();

        eventChooser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        R.setText("RELIGIOSO");
        R.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RActionPerformed(evt);
            }
        });
        eventChooser.add(R, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 180, 100));

        D.setText("DEPORTIVO");
        D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DActionPerformed(evt);
            }
        });
        eventChooser.add(D, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 180, 100));

        M.setText("MUSICAL");
        M.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MActionPerformed(evt);
            }
        });
        eventChooser.add(M, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 180, 100));

        CreateUserTemp.setBackground(new java.awt.Color(0, 0, 51));
        CreateUserTemp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        CreateUserTemp.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 340, 40));

        jLabel1.setText("Nombre Completo");
        CreateUserTemp.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, -1, -1));

        jLabel2.setText("Nombre de Usuario");
        CreateUserTemp.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, -1, -1));
        CreateUserTemp.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 340, 40));

        jLabel3.setText("Contraseña");
        CreateUserTemp.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 230, -1, -1));
        CreateUserTemp.add(pw, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 220, 340, 40));

        jLabel4.setText("Autoridad");
        CreateUserTemp.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 350, -1, -1));

        AgeSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", " " }));
        AgeSelector.setSelectedItem(0);
        CreateUserTemp.add(AgeSelector, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 350, -1, -1));

        create.setText("Crear Usuario");
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });
        CreateUserTemp.add(create, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 540, 220, 80));

        autoridad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Contenidos", "Limitado" }));
        autoridad.setSelectedItem(null);
        autoridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoridadActionPerformed(evt);
            }
        });
        CreateUserTemp.add(autoridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 340, 130, -1));

        jLabel5.setText("Edad");
        CreateUserTemp.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 350, -1, -1));

        SPORT.setBackground(new java.awt.Color(0, 0, 51));
        SPORT.setPreferredSize(new java.awt.Dimension(980, 590));
        SPORT.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        crearDeportivo.setText("Crear Evento");
        crearDeportivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearDeportivoActionPerformed(evt);
            }
        });
        SPORT.add(crearDeportivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 460, 220, 80));

        jLabel6.setText("NOMBRE DEL EVENTO");
        SPORT.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));
        SPORT.add(evName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 230, 40));

        jLabel7.setText("CODIGO");
        SPORT.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));
        SPORT.add(evCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 230, 40));

        jLabel8.setText("DESCRIPCION");
        SPORT.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, -1, -1));

        jLabel9.setText("RENTA");
        SPORT.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));
        SPORT.add(rent, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 230, 40));

        jLabel11.setText("EQUIPO 1");
        SPORT.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, -1, -1));
        SPORT.add(T1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, 230, 40));

        jLabel12.setText("EQUIPO 2");
        SPORT.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 310, -1, -1));
        SPORT.add(T2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 330, 230, 40));

        jLabel10.setText("FECHA");
        SPORT.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, -1));
        SPORT.add(cantPeople, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 230, 40));

        desc.setColumns(20);
        desc.setRows(5);
        jScrollPane1.setViewportView(desc);

        SPORT.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 400, 200));
        SPORT.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 230, 40));

        jLabel13.setText("CANT PERSONAS");
        SPORT.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        MUSICAL.setBackground(new java.awt.Color(0, 0, 51));
        MUSICAL.setPreferredSize(new java.awt.Dimension(980, 590));
        MUSICAL.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        crearDeportivo1.setText("Crear Evento");
        crearDeportivo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearDeportivo1ActionPerformed(evt);
            }
        });
        MUSICAL.add(crearDeportivo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 460, 220, 80));

        jLabel27.setText("NOMBRE DEL EVENTO");
        MUSICAL.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));
        MUSICAL.add(evName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 230, 40));

        jLabel28.setText("FECHA");
        MUSICAL.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, 20));

        jLabel29.setText("DESCRIPCION");
        MUSICAL.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, -1, -1));

        jLabel30.setText("RENTA");
        MUSICAL.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));
        MUSICAL.add(rent3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 230, 40));

        jLabel31.setText("EQUIPO 1");
        MUSICAL.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 280, -1, -1));

        jLabel33.setText("CANT PERSONAS");
        MUSICAL.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));
        MUSICAL.add(cantPeople3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 230, 40));

        desc3.setColumns(20);
        desc3.setRows(5);
        jScrollPane2.setViewportView(desc3);

        MUSICAL.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 400, 200));

        jLabel41.setText("CODIGO");
        MUSICAL.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));
        MUSICAL.add(evCode5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 230, 40));
        MUSICAL.add(dateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 230, 40));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        MUSICAL.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 320, 180, -1));

        RELIGIOSO.setBackground(new java.awt.Color(0, 0, 51));
        RELIGIOSO.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        crearDeportivo2.setText("Crear Evento");
        crearDeportivo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearDeportivo2ActionPerformed(evt);
            }
        });
        RELIGIOSO.add(crearDeportivo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 460, 220, 80));

        jLabel34.setText("NOMBRE DEL EVENTO");
        RELIGIOSO.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));
        RELIGIOSO.add(evName4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 230, 40));

        jLabel35.setText("CODIGO");
        RELIGIOSO.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));
        RELIGIOSO.add(evCode4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 230, 40));

        jLabel36.setText("DESCRIPCION");
        RELIGIOSO.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, -1, -1));

        jLabel37.setText("RENTA");
        RELIGIOSO.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));
        RELIGIOSO.add(rent4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 230, 40));

        jLabel38.setText("EQUIPO 1");
        RELIGIOSO.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, -1, -1));
        RELIGIOSO.add(T9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, 230, 40));

        jLabel39.setText("EQUIPO 2");
        RELIGIOSO.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 310, -1, -1));
        RELIGIOSO.add(T10, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 330, 230, 40));

        jLabel40.setText("CANT PERSONAS");
        RELIGIOSO.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));
        RELIGIOSO.add(cantPeople4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 230, 40));

        desc4.setColumns(20);
        desc4.setRows(5);
        jScrollPane3.setViewportView(desc4);

        RELIGIOSO.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 400, 200));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1920, 1080));

        MainLogin.setBackground(new java.awt.Color(0, 51, 102));
        MainLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoginBtn.setText("Iniciar Sesion");
        LoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtnActionPerformed(evt);
            }
        });
        MainLogin.add(LoginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 630, 330, 90));
        MainLogin.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 440, 370, 70));
        MainLogin.add(usernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 340, 370, 70));

        MainMenu.setBackground(new java.awt.Color(51, 0, 0));
        MainMenu.setPreferredSize(new java.awt.Dimension(1920, 1080));
        MainMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BACK2MENU.setText("Regresar al Menu Principal");
        MainMenu.add(BACK2MENU, new org.netbeans.lib.awtextra.AbsoluteConstraints(1730, 1010, 190, 50));

        CrearEvento.setText("Crear Evento");
        CrearEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearEventoActionPerformed(evt);
            }
        });
        MainMenu.add(CrearEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 290, 90));

        EditarEvento.setText("Editar Evento");
        EditarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarEventoActionPerformed(evt);
            }
        });
        MainMenu.add(EditarEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 290, 90));

        EliminarEvento.setText("Eliminar Evento");
        EliminarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarEventoActionPerformed(evt);
            }
        });
        MainMenu.add(EliminarEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 70, 290, 90));

        VerEvento.setText("Ver Evento");
        VerEvento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VerEventoMouseClicked(evt);
            }
        });
        MainMenu.add(VerEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 70, 290, 90));

        RealTime.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        RealTime.setText("DD/MM/YY");
        MainMenu.add(RealTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(1640, 30, 200, -1));

        tuner.setText("Administracion de Eventos");
        tuner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tunerActionPerformed(evt);
            }
        });
        MainMenu.add(tuner, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 460, 40));

        CrearUser.setText("Crear Usuario");
        CrearUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearUserActionPerformed(evt);
            }
        });
        MainMenu.add(CrearUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 290, 90));

        EditarUser.setText("Editar Usuario");
        EditarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarUserActionPerformed(evt);
            }
        });
        MainMenu.add(EditarUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 290, 90));

        EliminarUser.setText("Eliminar Usuario");
        EliminarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarUserActionPerformed(evt);
            }
        });
        MainMenu.add(EliminarUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 70, 290, 90));

        LOGOUT.setText("Cerrar Sesion");
        LOGOUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGOUTActionPerformed(evt);
            }
        });
        MainMenu.add(LOGOUT, new org.netbeans.lib.awtextra.AbsoluteConstraints(1730, 1010, 190, 50));

        verEVENTO.setPreferredSize(new java.awt.Dimension(980, 590));

        TITLE.setText("TIPO DE EVENTO");

        TITLE1.setText("CANTIDAD DE PERSONAS");

        cantidad_personas.setText("TIPO DE EVENTO");

        tipo_evento.setText("TIPO DE EVENTO");

        codigo_evento.setText("TIPO DE EVENTO");

        TITLE5.setText("TITULO");

        titulo_evento.setText("TIPO DE EVENTO");

        TITLE7.setText("CODIGO");

        TITLE8.setText("DESCRIPCION");

        descripcion_evento.setText("TIPO DE EVENTO");

        TITLE9.setText("FECHA");

        fecha_evento.setText("TIPO DE EVENTO");

        TITLE10.setText("Equipo 1");

        equipo1_evento.setText("TIPO DE EVENTO");

        TITLE11.setText("Equipo 2");

        equipo2_evento.setText("TIPO DE EVENTO");

        TITLE12.setText("Musicos");

        equipo2_evento1.setText("TIPO DE EVENTO");

        TITLE13.setText("Equipo 2");

        equipo2_evento2.setText("TIPO DE EVENTO");

        TITLE14.setText("Equipo 2");

        equipo2_evento3.setText("TIPO DE EVENTO");

        teamList2_evento.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(teamList2_evento);

        musicosYcargo_evento.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(musicosYcargo_evento);

        teamList1_evento2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane6.setViewportView(teamList1_evento2);

        javax.swing.GroupLayout verEVENTOLayout = new javax.swing.GroupLayout(verEVENTO);
        verEVENTO.setLayout(verEVENTOLayout);
        verEVENTOLayout.setHorizontalGroup(
            verEVENTOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verEVENTOLayout.createSequentialGroup()
                .addGroup(verEVENTOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(verEVENTOLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(TITLE, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(tipo_evento, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(verEVENTOLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(TITLE1)
                        .addGap(18, 18, 18)
                        .addComponent(cantidad_personas, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(verEVENTOLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(verEVENTOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(verEVENTOLayout.createSequentialGroup()
                                .addComponent(TITLE11, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(equipo2_evento, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(verEVENTOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(verEVENTOLayout.createSequentialGroup()
                                    .addComponent(TITLE10, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(29, 29, 29)
                                    .addComponent(equipo1_evento, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(verEVENTOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(verEVENTOLayout.createSequentialGroup()
                                        .addComponent(TITLE8, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addComponent(descripcion_evento, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(verEVENTOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(verEVENTOLayout.createSequentialGroup()
                                            .addComponent(TITLE5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(titulo_evento, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(verEVENTOLayout.createSequentialGroup()
                                            .addGap(24, 24, 24)
                                            .addComponent(TITLE7)
                                            .addGap(50, 50, 50)
                                            .addComponent(codigo_evento, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(verEVENTOLayout.createSequentialGroup()
                                        .addComponent(TITLE9, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addComponent(fecha_evento, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(verEVENTOLayout.createSequentialGroup()
                                .addComponent(TITLE12, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(equipo2_evento1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(verEVENTOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(verEVENTOLayout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(TITLE14, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(29, 29, 29)
                                    .addComponent(equipo2_evento3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(verEVENTOLayout.createSequentialGroup()
                                    .addComponent(TITLE13, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(29, 29, 29)
                                    .addComponent(equipo2_evento2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(6, 6, 6))))
                        .addGroup(verEVENTOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(verEVENTOLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, verEVENTOLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(272, Short.MAX_VALUE))
        );
        verEVENTOLayout.setVerticalGroup(
            verEVENTOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verEVENTOLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(verEVENTOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TITLE, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipo_evento, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(verEVENTOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TITLE1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cantidad_personas, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(verEVENTOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TITLE7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codigo_evento, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(verEVENTOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TITLE5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titulo_evento, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(verEVENTOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TITLE8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descripcion_evento, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(verEVENTOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TITLE9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fecha_evento, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(verEVENTOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(verEVENTOLayout.createSequentialGroup()
                        .addGroup(verEVENTOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TITLE10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(equipo1_evento, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(verEVENTOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TITLE11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(equipo2_evento, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(verEVENTOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, verEVENTOLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(verEVENTOLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(verEVENTOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TITLE12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(equipo2_evento1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addGroup(verEVENTOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TITLE13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(equipo2_evento2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(verEVENTOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TITLE14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(equipo2_evento3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34))))
        );

        MainMenu.add(verEVENTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(MainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(MainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void LoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBtnActionPerformed
        if (!usernameField.getText().isBlank() && !passwordField.getText().isBlank()) {

            if (toolKit.Login(usernameField.getText(), passwordField.getText(), usuarios)) {
                loggeado = usernameField.getText();
                usernameField.setText("");
                passwordField.setText("");
                System.out.println("passed!");
                System.out.println(loggeado);
                MainLogin.setVisible(false);
                MainMenu.setVisible(true);

            }

        } else {
            JOptionPane.showMessageDialog(null, "Por favor llene todos los campos");
        }
    }//GEN-LAST:event_LoginBtnActionPerformed

    private void CrearEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearEventoActionPerformed
        EditarEvento.setVisible(false);
        EliminarEvento.setVisible(false);
        VerEvento.setVisible(false);

        eventChooser.setVisible(true);
    }//GEN-LAST:event_CrearEventoActionPerformed

    private void EditarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarEventoActionPerformed
        CrearEvento.setVisible(false);
        EliminarEvento.setVisible(false);
        VerEvento.setVisible(false);

    }//GEN-LAST:event_EditarEventoActionPerformed

    private void EliminarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarEventoActionPerformed
        CrearEvento.setVisible(false);
        EditarEvento.setVisible(false);
        VerEvento.setVisible(false);
    }//GEN-LAST:event_EliminarEventoActionPerformed

    private void tunerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tunerActionPerformed
        TUNER(CrearEvento, EditarEvento, EliminarEvento, VerEvento, CrearUser, EditarUser, EliminarUser, tuner);
        CreateUserTemp.setVisible(false);
        eventChooser.setVisible(false);
        MUSICAL.setVisible(false);
        SPORT.setVisible(false);
        RELIGIOSO.setVisible(false);

    }//GEN-LAST:event_tunerActionPerformed

    private void CrearUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearUserActionPerformed
        if (!CreateUserTemp.isVisible()) {
            CreateUserTemp.setVisible(true);
        } else if (CreateUserTemp.isVisible()) {
            CreateUserTemp.setVisible(false);
        }

    }//GEN-LAST:event_CrearUserActionPerformed

    private void EditarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditarUserActionPerformed

    private void EliminarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EliminarUserActionPerformed

    private void LOGOUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGOUTActionPerformed
        LogOut(MainLogin, MainMenu);
    }//GEN-LAST:event_LOGOUTActionPerformed

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed

        if (!fname.getText().isBlank() && !usuario.getText().isBlank() && AgeSelector.getSelectedItem() != null && autoridad.getSelectedItem() != null) {

            String range = autoridad.getSelectedItem().toString();
            String eda = AgeSelector.getSelectedItem().toString();
            int ed = Integer.parseInt(eda);

            toolKit.crear(fname.getText(), usuario.getText(), pw.getText(), range, ed, usuarios);
            CreateUserTemp.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "Llene todos los campos solicitados");
        }

        fname.setText("");
        usuario.setText("");
        pw.setText("");


    }//GEN-LAST:event_createActionPerformed

    private void autoridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoridadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_autoridadActionPerformed

    private void crearDeportivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearDeportivoActionPerformed
        String name;

        if (!evName.getText().isBlank() && !evCode.getText().isBlank() && !desc.getText().isBlank() && !cantPeople.getText().isBlank() && !T1.getText().isBlank() && !T2.getText().isBlank()) {
            tk.createEvent(Integer.parseInt(cantPeople.getText()), Integer.parseInt(evCode.getText()), evName.getText(), desc.getText(), fechita, Double.parseDouble(rent.getText()), event.DEPORTIVO, music, sport.FUTBOL, T1.getText(), T2.getText());
            this.evName.setText(null);
            this.evCode.setText(null);
            this.desc.setText(null);
            this.rent.setText(null);
            this.cantPeople.setText(null);
            this.T1.setText(null);
            this.T2.setText(null);
        } else {
            JOptionPane.showMessageDialog(null, "Llene todos los campos por favor");
        }


    }//GEN-LAST:event_crearDeportivoActionPerformed

    private void DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DActionPerformed
        eventChooser.setVisible(false);
        SPORT.setVisible(true);
        MUSICAL.setVisible(false);
        RELIGIOSO.setVisible(false);
    }//GEN-LAST:event_DActionPerformed

    private void MActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MActionPerformed
        eventChooser.setVisible(false);
        MUSICAL.setVisible(true);
        SPORT.setVisible(false);
        RELIGIOSO.setVisible(false);
    }//GEN-LAST:event_MActionPerformed

    private void RActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RActionPerformed
        eventChooser.setVisible(false);
        RELIGIOSO.setVisible(true);
        MUSICAL.setVisible(false);
        SPORT.setVisible(false);
    }//GEN-LAST:event_RActionPerformed

    private void crearDeportivo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearDeportivo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crearDeportivo1ActionPerformed

    private void crearDeportivo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearDeportivo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crearDeportivo2ActionPerformed

    private void VerEventoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VerEventoMouseClicked
        CrearEvento.setVisible(false);
        EditarEvento.setVisible(false);
        EliminarEvento.setVisible(false);
        VerEvento.setLocation(CrearEvento.getLocation());
       
        
    }//GEN-LAST:event_VerEventoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sistema().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AgeSelector;
    private javax.swing.JButton BACK2MENU;
    private javax.swing.JButton CrearEvento;
    private javax.swing.JButton CrearUser;
    private javax.swing.JPanel CreateUserTemp;
    private javax.swing.JButton D;
    private javax.swing.JButton EditarEvento;
    private javax.swing.JButton EditarUser;
    private javax.swing.JButton EliminarEvento;
    private javax.swing.JButton EliminarUser;
    private javax.swing.JButton LOGOUT;
    private javax.swing.JButton LoginBtn;
    private javax.swing.JButton M;
    private javax.swing.JPanel MUSICAL;
    private javax.swing.JPanel MainLogin;
    private javax.swing.JPanel MainMenu;
    private javax.swing.JButton R;
    private javax.swing.JPanel RELIGIOSO;
    private javax.swing.JLabel RealTime;
    private javax.swing.JPanel SPORT;
    private javax.swing.JTextField T1;
    private javax.swing.JTextField T10;
    private javax.swing.JTextField T2;
    private javax.swing.JTextField T9;
    private javax.swing.JLabel TITLE;
    private javax.swing.JLabel TITLE1;
    private javax.swing.JLabel TITLE10;
    private javax.swing.JLabel TITLE11;
    private javax.swing.JLabel TITLE12;
    private javax.swing.JLabel TITLE13;
    private javax.swing.JLabel TITLE14;
    private javax.swing.JLabel TITLE5;
    private javax.swing.JLabel TITLE7;
    private javax.swing.JLabel TITLE8;
    private javax.swing.JLabel TITLE9;
    private javax.swing.JButton VerEvento;
    private javax.swing.JComboBox<String> autoridad;
    private javax.swing.JTextField cantPeople;
    private javax.swing.JTextField cantPeople3;
    private javax.swing.JTextField cantPeople4;
    private javax.swing.JLabel cantidad_personas;
    private javax.swing.JLabel codigo_evento;
    private javax.swing.JToggleButton crearDeportivo;
    private javax.swing.JToggleButton crearDeportivo1;
    private javax.swing.JToggleButton crearDeportivo2;
    private javax.swing.JToggleButton create;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JTextArea desc;
    private javax.swing.JTextArea desc3;
    private javax.swing.JTextArea desc4;
    private javax.swing.JLabel descripcion_evento;
    private javax.swing.JLabel equipo1_evento;
    private javax.swing.JLabel equipo2_evento;
    private javax.swing.JLabel equipo2_evento1;
    private javax.swing.JLabel equipo2_evento2;
    private javax.swing.JLabel equipo2_evento3;
    private javax.swing.JTextField evCode;
    private javax.swing.JTextField evCode4;
    private javax.swing.JTextField evCode5;
    private javax.swing.JTextField evName;
    private javax.swing.JTextField evName3;
    private javax.swing.JTextField evName4;
    private javax.swing.JPanel eventChooser;
    private javax.swing.JLabel fecha_evento;
    private javax.swing.JTextField fname;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JList<String> musicosYcargo_evento;
    private javax.swing.JTextField passwordField;
    private javax.swing.JTextField pw;
    private javax.swing.JTextField rent;
    private javax.swing.JTextField rent3;
    private javax.swing.JTextField rent4;
    private javax.swing.JList<String> teamList1_evento2;
    private javax.swing.JList<String> teamList2_evento;
    private javax.swing.JLabel tipo_evento;
    private javax.swing.JLabel titulo_evento;
    private javax.swing.JButton tuner;
    private javax.swing.JTextField usernameField;
    private javax.swing.JTextField usuario;
    private javax.swing.JPanel verEVENTO;
    // End of variables declaration//GEN-END:variables
}
