package GUI;

import Eventos.Enums.tipoDeporte;
import Eventos.Enums.tipoEvento;
import Eventos.Enums.tipoMusica;
import Eventos.Evento;
import Usuarios.UsuarioDefault;
import java.awt.Point;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Josue Gavidia
 */
public class Sistema extends javax.swing.JFrame {

    Calendar fechita = Calendar.getInstance();
    UsuarioDefault toolKit;
    private static Date FECHA = new Date();
    private static SimpleDateFormat fechaLive = new SimpleDateFormat("dd/MM/yyyy");

    //CORE ---> ARREGLOS QUE CONTIENEN EVENTOS Y USUARIOS
    private UsuarioDefault usuarios[];
    private Evento tk;
    final String fullNameDefault = "Erick Amaya";
    final int ageDefault = 32;
    final String userDefault = "admin";
    final String passDefault = "supersecreto";
    final String rangoDefault = "administrador";
    public String loggeado;
    private tipoEvento event;
    private tipoDeporte sport;
    private tipoMusica music;

    public Sistema() throws NullPointerException {

        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        tk = new Evento(0,0,"","",fechita,0.0);
        toolKit = new UsuarioDefault(fullNameDefault, userDefault, passDefault, rangoDefault, ageDefault);
        usuarios = new UsuarioDefault[10];
        usuarios[0] = toolKit;
        initWindows();
        this.AgeSelector.setSelectedItem(null);
        this.autoridad.setSelectedItem(null);
        this.RealTime.setText(fechaLive.format(FECHA));

    }

    //MISC METHODS
    //Could be implemented with an interface
    public final void initWindows() {
        MainLogin.setVisible(true);
        MainMenu.setVisible(false);
        BACK2MENU.setVisible(false);
        CrearUser.setVisible(false);
        EditarUser.setVisible(false);
        EliminarUser.setVisible(false);
        CreateUserTemp.setVisible(false);
        SPORT.setVisible(false);
        MUSICAL.setVisible(false);
        RELIGIOSO.setVisible(false);
        eventChooser.setVisible(false);
    }

    public void TUNER(JButton crearEv, JButton editEv, JButton elimEv, JButton verEv, JButton crearUs, JButton editUs, JButton elimUs, JButton tune) {
        JButton[] eventos = {crearEv, editEv, elimEv, verEv};
        JButton[] usuario = {crearUs, editUs, elimUs};

        if (tuner.getText().equals("Administracion de Eventos")) {
            for (int i = 0; i < eventos.length; i++) {
                for (int j = 0; j < usuario.length; j++) {
                    eventos[i].setVisible(false);
                    usuario[j].setVisible(true);
                    tune.setText("Administracion de Usuarios");

                }

            }
        } else if (tuner.getText().equals("Administracion de Usuarios")) {
            for (int k = 0; k < eventos.length; k++) {
                for (int l = 0; l < usuario.length; l++) {
                    eventos[k].setVisible(true);
                    usuario[l].setVisible(false);
                    tune.setText("Administracion de Eventos");
                }

            }
        }

    }

    public void LogOut(JPanel login, JPanel mainMenu) {
        login.setVisible(true);
        mainMenu.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CreateUserTemp = new javax.swing.JPanel();
        fname = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pw = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        AgeSelector = new javax.swing.JComboBox<>();
        create = new javax.swing.JToggleButton();
        autoridad = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        MainLogin = new javax.swing.JPanel();
        LoginBtn = new javax.swing.JButton();
        passwordField = new javax.swing.JTextField();
        usernameField = new javax.swing.JTextField();
        MainMenu = new javax.swing.JPanel();
        eventChooser = new javax.swing.JPanel();
        R = new javax.swing.JButton();
        D = new javax.swing.JButton();
        M = new javax.swing.JButton();
        BACK2MENU = new javax.swing.JButton();
        CrearEvento = new javax.swing.JButton();
        EditarEvento = new javax.swing.JButton();
        EliminarEvento = new javax.swing.JButton();
        VerEvento = new javax.swing.JButton();
        RealTime = new javax.swing.JLabel();
        tuner = new javax.swing.JButton();
        CrearUser = new javax.swing.JButton();
        EditarUser = new javax.swing.JButton();
        EliminarUser = new javax.swing.JButton();
        LOGOUT = new javax.swing.JButton();
        MUSICAL = new javax.swing.JPanel();
        crearEvento1 = new javax.swing.JToggleButton();
        jLabel13 = new javax.swing.JLabel();
        evName1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        evCode1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        desc1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        rent1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        T3 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        T4 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        cantPeople1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        RELIGIOSO = new javax.swing.JPanel();
        crearReligioso = new javax.swing.JToggleButton();
        jLabel20 = new javax.swing.JLabel();
        evName2 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        evCode2 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        desc2 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        rent2 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        T5 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        T6 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        cantPeople2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        SPORT = new javax.swing.JPanel();
        crearDeportivo = new javax.swing.JToggleButton();
        jLabel6 = new javax.swing.JLabel();
        evName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        evCode = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        desc = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        rent = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        T1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        T2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cantPeople = new javax.swing.JTextField();

        CreateUserTemp.setBackground(new java.awt.Color(0, 0, 51));
        CreateUserTemp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        CreateUserTemp.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 340, 40));

        jLabel1.setText("Nombre Completo");
        CreateUserTemp.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, -1, -1));

        jLabel2.setText("Nombre de Usuario");
        CreateUserTemp.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, -1, -1));
        CreateUserTemp.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 340, 40));

        jLabel3.setText("Contraseña");
        CreateUserTemp.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 230, -1, -1));
        CreateUserTemp.add(pw, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 220, 340, 40));

        jLabel4.setText("Autoridad");
        CreateUserTemp.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 350, -1, -1));

        AgeSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", " " }));
        AgeSelector.setSelectedItem(0);
        CreateUserTemp.add(AgeSelector, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 350, -1, -1));

        create.setText("Crear Usuario");
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });
        CreateUserTemp.add(create, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 540, 220, 80));

        autoridad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Contenidos", "Limitado" }));
        autoridad.setSelectedItem(null);
        autoridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoridadActionPerformed(evt);
            }
        });
        CreateUserTemp.add(autoridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 340, 130, -1));

        jLabel5.setText("Edad");
        CreateUserTemp.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 350, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1920, 1080));

        MainLogin.setBackground(new java.awt.Color(0, 51, 102));
        MainLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoginBtn.setText("Iniciar Sesion");
        LoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtnActionPerformed(evt);
            }
        });
        MainLogin.add(LoginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 630, 330, 90));
        MainLogin.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 440, 370, 70));
        MainLogin.add(usernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 340, 370, 70));

        MainMenu.setBackground(new java.awt.Color(51, 0, 0));
        MainMenu.setPreferredSize(new java.awt.Dimension(1920, 1080));
        MainMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        eventChooser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        R.setText("RELIGIOSO");
        R.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RActionPerformed(evt);
            }
        });
        eventChooser.add(R, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 180, 100));

        D.setText("DEPORTIVO");
        D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DActionPerformed(evt);
            }
        });
        eventChooser.add(D, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 180, 100));

        M.setText("MUSICAL");
        M.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MActionPerformed(evt);
            }
        });
        eventChooser.add(M, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 180, 100));

        MainMenu.add(eventChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 670, 360));

        BACK2MENU.setText("Regresar al Menu Principal");
        MainMenu.add(BACK2MENU, new org.netbeans.lib.awtextra.AbsoluteConstraints(1730, 1010, 190, 50));

        CrearEvento.setText("Crear Evento");
        CrearEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearEventoActionPerformed(evt);
            }
        });
        MainMenu.add(CrearEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 290, 90));

        EditarEvento.setText("Editar Evento");
        EditarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarEventoActionPerformed(evt);
            }
        });
        MainMenu.add(EditarEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 290, 90));

        EliminarEvento.setText("Eliminar Evento");
        EliminarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarEventoActionPerformed(evt);
            }
        });
        MainMenu.add(EliminarEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 70, 290, 90));

        VerEvento.setText("Ver Evento");
        VerEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerEventoActionPerformed(evt);
            }
        });
        MainMenu.add(VerEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 70, 290, 90));

        RealTime.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        RealTime.setText("DD/MM/YY");
        MainMenu.add(RealTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(1640, 30, 200, -1));

        tuner.setText("Administracion de Eventos");
        tuner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tunerActionPerformed(evt);
            }
        });
        MainMenu.add(tuner, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 460, 40));

        CrearUser.setText("Crear Usuario");
        CrearUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearUserActionPerformed(evt);
            }
        });
        MainMenu.add(CrearUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 290, 90));

        EditarUser.setText("Editar Usuario");
        EditarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarUserActionPerformed(evt);
            }
        });
        MainMenu.add(EditarUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 290, 90));

        EliminarUser.setText("Eliminar Usuario");
        EliminarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarUserActionPerformed(evt);
            }
        });
        MainMenu.add(EliminarUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 70, 290, 90));

        LOGOUT.setText("Cerrar Sesion");
        LOGOUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGOUTActionPerformed(evt);
            }
        });
        MainMenu.add(LOGOUT, new org.netbeans.lib.awtextra.AbsoluteConstraints(1730, 1010, 190, 50));

        MUSICAL.setBackground(new java.awt.Color(0, 0, 51));
        MUSICAL.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        crearEvento1.setText("Crear Evento");
        crearEvento1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearEvento1ActionPerformed(evt);
            }
        });
        MUSICAL.add(crearEvento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 540, 220, 80));

        jLabel13.setText("NOMBRE DEL EVENTO");
        MUSICAL.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, -1));
        MUSICAL.add(evName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 230, 40));

        jLabel14.setText("CODIGO");
        MUSICAL.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, -1));
        MUSICAL.add(evCode1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 230, 40));

        jLabel15.setText("DESCRIPCION");
        MUSICAL.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, -1, -1));
        MUSICAL.add(desc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 230, 40));

        jLabel16.setText("RENTA");
        MUSICAL.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, -1, -1));
        MUSICAL.add(rent1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, 230, 40));

        jLabel17.setText("EQUIPO 1");
        MUSICAL.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, -1, -1));
        MUSICAL.add(T3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 150, 230, 40));

        jLabel18.setText("EQUIPO 2");
        MUSICAL.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 260, -1, -1));
        MUSICAL.add(T4, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 250, 230, 40));

        jLabel19.setText("CANT PERSONAS");
        MUSICAL.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, -1, -1));
        MUSICAL.add(cantPeople1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, 230, 40));

        jButton1.setText("MUSIC");
        MUSICAL.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 240, -1, -1));

        MainMenu.add(MUSICAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 1670, 820));

        RELIGIOSO.setBackground(new java.awt.Color(0, 0, 51));
        RELIGIOSO.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        crearReligioso.setText("Crear Evento");
        crearReligioso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearReligiosoActionPerformed(evt);
            }
        });
        RELIGIOSO.add(crearReligioso, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 540, 220, 80));

        jLabel20.setText("NOMBRE DEL EVENTO");
        RELIGIOSO.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, -1));
        RELIGIOSO.add(evName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 230, 40));

        jLabel21.setText("CODIGO");
        RELIGIOSO.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, -1));
        RELIGIOSO.add(evCode2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 230, 40));

        jLabel22.setText("DESCRIPCION");
        RELIGIOSO.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, -1, -1));
        RELIGIOSO.add(desc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 230, 40));

        jLabel23.setText("RENTA");
        RELIGIOSO.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, -1, -1));
        RELIGIOSO.add(rent2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, 230, 40));

        jLabel24.setText("EQUIPO 1");
        RELIGIOSO.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, -1, -1));
        RELIGIOSO.add(T5, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 150, 230, 40));

        jLabel25.setText("EQUIPO 2");
        RELIGIOSO.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 260, -1, -1));
        RELIGIOSO.add(T6, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 250, 230, 40));

        jLabel26.setText("CANT PERSONAS");
        RELIGIOSO.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, -1, -1));
        RELIGIOSO.add(cantPeople2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, 230, 40));

        jButton2.setText("RELIGIOUS");
        RELIGIOSO.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 240, -1, -1));

        MainMenu.add(RELIGIOSO, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 1670, 820));

        SPORT.setBackground(new java.awt.Color(0, 0, 51));
        SPORT.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        crearDeportivo.setText("Crear Evento");
        crearDeportivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearDeportivoActionPerformed(evt);
            }
        });
        SPORT.add(crearDeportivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 540, 220, 80));

        jLabel6.setText("NOMBRE DEL EVENTO");
        SPORT.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, -1));
        SPORT.add(evName, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 230, 40));

        jLabel7.setText("CODIGO");
        SPORT.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, -1));
        SPORT.add(evCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 230, 40));

        jLabel8.setText("DESCRIPCION");
        SPORT.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, -1, -1));
        SPORT.add(desc, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 230, 40));

        jLabel9.setText("RENTA");
        SPORT.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, -1, -1));
        SPORT.add(rent, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, 230, 40));

        jLabel11.setText("EQUIPO 1");
        SPORT.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, -1, -1));
        SPORT.add(T1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 150, 230, 40));

        jLabel12.setText("EQUIPO 2");
        SPORT.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 260, -1, -1));
        SPORT.add(T2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 250, 230, 40));

        jLabel10.setText("CANT PERSONAS");
        SPORT.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, -1, -1));
        SPORT.add(cantPeople, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, 230, 40));

        MainMenu.add(SPORT, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 1670, 820));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(MainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(MainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void LoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBtnActionPerformed
        if (!usernameField.getText().isBlank() && !passwordField.getText().isBlank()) {

            if (toolKit.Login(usernameField.getText(), passwordField.getText(), usuarios, loggeado)) {
                usernameField.setText("");
                passwordField.setText("");
                System.out.println("passed!");
                MainLogin.setVisible(false);
                MainMenu.setVisible(true);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Por favor llene todos los campos");
        }
    }//GEN-LAST:event_LoginBtnActionPerformed

    private void CrearEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearEventoActionPerformed
        EditarEvento.setVisible(false);
        EliminarEvento.setVisible(false);
        VerEvento.setVisible(false);

        eventChooser.setVisible(true);
    }//GEN-LAST:event_CrearEventoActionPerformed

    private void EditarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarEventoActionPerformed
        CrearEvento.setVisible(false);
        EliminarEvento.setVisible(false);
        VerEvento.setVisible(false);

    }//GEN-LAST:event_EditarEventoActionPerformed

    private void EliminarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarEventoActionPerformed
        CrearEvento.setVisible(false);
        EditarEvento.setVisible(false);
        VerEvento.setVisible(false);
    }//GEN-LAST:event_EliminarEventoActionPerformed

    private void VerEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerEventoActionPerformed
        Point x = CrearEvento.getLocation();

        VerEvento.setLocation(x);
        CrearEvento.setVisible(false);
        EditarEvento.setVisible(false);
        EliminarEvento.setVisible(false);

    }//GEN-LAST:event_VerEventoActionPerformed

    private void tunerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tunerActionPerformed
        TUNER(CrearEvento, EditarEvento, EliminarEvento, VerEvento, CrearUser, EditarUser, EliminarUser, tuner);
        eventChooser.setVisible(false);
       MUSICAL.setVisible(false);
        SPORT.setVisible(false);
       RELIGIOSO.setVisible(false);
        
    }//GEN-LAST:event_tunerActionPerformed

    private void CrearUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearUserActionPerformed
        if (!CreateUserTemp.isVisible()) {
            CreateUserTemp.setVisible(true);
        } else if (CreateUserTemp.isVisible()) {
            CreateUserTemp.setVisible(false);
        }

    }//GEN-LAST:event_CrearUserActionPerformed

    private void EditarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditarUserActionPerformed

    private void EliminarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EliminarUserActionPerformed

    private void LOGOUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGOUTActionPerformed
        LogOut(MainLogin, MainMenu);
    }//GEN-LAST:event_LOGOUTActionPerformed

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed

        if (!fname.getText().isBlank() && !usuario.getText().isBlank() && AgeSelector.getSelectedItem() != null && autoridad.getSelectedItem() != null) {

            String range = autoridad.getSelectedItem().toString();
            String eda = AgeSelector.getSelectedItem().toString();
            int ed = Integer.parseInt(eda);

            toolKit.crear(fname.getText(), usuario.getText(), pw.getText(), range, ed, usuarios);
            CreateUserTemp.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "Llene todos los campos solicitados");
        }

        fname.setText("");
        usuario.setText("");
        pw.setText("");


    }//GEN-LAST:event_createActionPerformed

    private void autoridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoridadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_autoridadActionPerformed

    private void crearDeportivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearDeportivoActionPerformed
    tk.createEvent(Integer.parseInt(cantPeople.getText()), Integer.parseInt(evCode.getText()), evName.getText(), desc.getText(), fechita, Double.parseDouble(rent.getText()), event.DEPORTIVO, music, sport.FUTBOL, T1.getText(), T2.getText());
    this.evName.setText(null);
    this.evCode.setText(null);
    this.desc.setText(null);
    this.rent.setText(null);
    this.cantPeople.setText(null);
    this.T1.setText(null);
    this.T2.setText(null);
    }//GEN-LAST:event_crearDeportivoActionPerformed

    private void crearEvento1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearEvento1ActionPerformed
        // TODO add your handling code here:\\\\\\\\\\
    }//GEN-LAST:event_crearEvento1ActionPerformed

    private void crearReligiosoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearReligiosoActionPerformed
        tk.createEvent(Integer.parseInt(cantPeople1.getText()), Integer.parseInt(evCode1.getText()), evName1.getText(), desc1.getText(), fechita, Double.parseDouble(rent1.getText()), event.DEPORTIVO, music, sport.FUTBOL, T5.getText(), T6.getText());
    }//GEN-LAST:event_crearReligiosoActionPerformed

    private void DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DActionPerformed
       eventChooser.setVisible(false);
       SPORT.setVisible(true);
       MUSICAL.setVisible(false);
       RELIGIOSO.setVisible(false);
    }//GEN-LAST:event_DActionPerformed

    private void MActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MActionPerformed
         eventChooser.setVisible(false);
       MUSICAL.setVisible(true);
        SPORT.setVisible(false);
       RELIGIOSO.setVisible(false);
    }//GEN-LAST:event_MActionPerformed

    private void RActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RActionPerformed
        eventChooser.setVisible(false);
       RELIGIOSO .setVisible(true);
        MUSICAL.setVisible(false);
       SPORT.setVisible(false);
    }//GEN-LAST:event_RActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sistema().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AgeSelector;
    private javax.swing.JButton BACK2MENU;
    private javax.swing.JButton CrearEvento;
    private javax.swing.JButton CrearUser;
    private javax.swing.JPanel CreateUserTemp;
    private javax.swing.JButton D;
    private javax.swing.JButton EditarEvento;
    private javax.swing.JButton EditarUser;
    private javax.swing.JButton EliminarEvento;
    private javax.swing.JButton EliminarUser;
    private javax.swing.JButton LOGOUT;
    private javax.swing.JButton LoginBtn;
    private javax.swing.JButton M;
    private javax.swing.JPanel MUSICAL;
    private javax.swing.JPanel MainLogin;
    private javax.swing.JPanel MainMenu;
    private javax.swing.JButton R;
    private javax.swing.JPanel RELIGIOSO;
    private javax.swing.JLabel RealTime;
    private javax.swing.JPanel SPORT;
    private javax.swing.JTextField T1;
    private javax.swing.JTextField T2;
    private javax.swing.JTextField T3;
    private javax.swing.JTextField T4;
    private javax.swing.JTextField T5;
    private javax.swing.JTextField T6;
    private javax.swing.JButton VerEvento;
    private javax.swing.JComboBox<String> autoridad;
    private javax.swing.JTextField cantPeople;
    private javax.swing.JTextField cantPeople1;
    private javax.swing.JTextField cantPeople2;
    private javax.swing.JToggleButton crearDeportivo;
    private javax.swing.JToggleButton crearEvento1;
    private javax.swing.JToggleButton crearReligioso;
    private javax.swing.JToggleButton create;
    private javax.swing.JTextField desc;
    private javax.swing.JTextField desc1;
    private javax.swing.JTextField desc2;
    private javax.swing.JTextField evCode;
    private javax.swing.JTextField evCode1;
    private javax.swing.JTextField evCode2;
    private javax.swing.JTextField evName;
    private javax.swing.JTextField evName1;
    private javax.swing.JTextField evName2;
    private javax.swing.JPanel eventChooser;
    private javax.swing.JTextField fname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField passwordField;
    private javax.swing.JTextField pw;
    private javax.swing.JTextField rent;
    private javax.swing.JTextField rent1;
    private javax.swing.JTextField rent2;
    private javax.swing.JButton tuner;
    private javax.swing.JTextField usernameField;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
