
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Josue Gavidia
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
  
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SALIR = new javax.swing.JButton();
        BACK2LOGIN = new javax.swing.JButton();
        ADMINEVS = new javax.swing.JButton();
        AdminUsuarios1 = new javax.swing.JButton();
        BACK2LOGIN1 = new javax.swing.JButton();
        REPORTES = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SALIR.setText("Salir");
        SALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SALIRActionPerformed(evt);
            }
        });
        jPanel1.add(SALIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 240, 70));

        BACK2LOGIN.setText("Cerrar sesion");
        BACK2LOGIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACK2LOGINActionPerformed(evt);
            }
        });
        jPanel1.add(BACK2LOGIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 540, 150, 30));

        ADMINEVS.setText("ADMINISTRACION DE EVENTOS");
        ADMINEVS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADMINEVSActionPerformed(evt);
            }
        });
        jPanel1.add(ADMINEVS, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 240, 70));

        AdminUsuarios1.setText("ADMINISTRACION DE  USUARIOS");
        AdminUsuarios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminUsuarios1ActionPerformed(evt);
            }
        });
        jPanel1.add(AdminUsuarios1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 240, 70));

        BACK2LOGIN1.setText("Cerrar sesion");
        BACK2LOGIN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACK2LOGIN1ActionPerformed(evt);
            }
        });
        jPanel1.add(BACK2LOGIN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 540, 150, 30));

        REPORTES.setText("REPORTES");
        REPORTES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REPORTESActionPerformed(evt);
            }
        });
        jPanel1.add(REPORTES, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 240, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void SALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SALIRActionPerformed
       System.exit(0);
    }//GEN-LAST:event_SALIRActionPerformed

    private void BACK2LOGINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACK2LOGINActionPerformed
        Login log = new Login();
        log.setVisible(true);
        log.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_BACK2LOGINActionPerformed

    private void ADMINEVSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADMINEVSActionPerformed
         
        
        if(CrearUserGUI.tipoUser.equals("admin")||CrearUserGUI.tipoUser.equals("contenidos")||Login.user.equals("admin")){
        EventsManager EVmanager = new  EventsManager();
        EVmanager.setVisible(true);
         EVmanager.setLocationRelativeTo(null);
        this.setVisible(false);
        }else{
             JOptionPane.showMessageDialog(rootPane, "Opcion no disponible para este tipo de Usuario");
        }        
    }//GEN-LAST:event_ADMINEVSActionPerformed

    private void AdminUsuarios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminUsuarios1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminUsuarios1ActionPerformed

    private void BACK2LOGIN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACK2LOGIN1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BACK2LOGIN1ActionPerformed

    private void REPORTESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REPORTESActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_REPORTESActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADMINEVS;
    private javax.swing.JButton AdminUsuarios1;
    private javax.swing.JButton BACK2LOGIN;
    private javax.swing.JButton BACK2LOGIN1;
    private javax.swing.JButton REPORTES;
    private javax.swing.JButton SALIR;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
